#!/bin/bash

# W specific pxPP libraries are run this time (as run2) with a larger insert size, as opposed to earlier 200-500 range

SEQDATA_DIR=/data/illum/141219_M01442_0148_000000000-AC0PP/Project_Avanthof_6325_1

echo " Processing $SEQDATA_DIR"

SAMPLE=1
MEDIAN_INSERT_SIZE=500
MIN_INSERT_SIZE=200
MAX_INSERT_SIZE=1000
LIBRARY=PLUTHGAP_RUN2

BOWTIE_INDEX=$HOME/Plutella/sequenceStorage/HGAP_NOV2014_polished
OUTPUT_DIR=$HOME/Plutella/BowtieMappings/HGAP_polished_run2

RGINFO="--rg-id sample:$SAMPLE --rg SM:$SAMPLE --rg LB:$LIBRARY --rg PI:$MEDIAN_INSERT_SIZE --rg PL:ILLUMINA"
PAIR_MAP_ARGS="--fr -I $MIN_INSERT_SIZE -X $MAX_INSERT_SIZE"	

# pxPP4 sample
PAIR_1=$SEQDATA_DIR/Sample_1-PxPP4/1-PxPP4_ATTACTCG-TATAGCCT_L001_R1_001.fastq.gz
PAIR_2=$SEQDATA_DIR/Sample_1-PxPP4/1-PxPP4_ATTACTCG-TATAGCCT_L001_R2_001.fastq.gz
SAM_OUT=$OUTPUT_DIR/$LIBRARY.pxPP4.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &

# pxPP7 sample
PAIR_1=$SEQDATA_DIR/Sample_3-PxPP7/3-PxPP7_TCCGGAGA-TATAGCCT_L001_R1_001.fastq.gz
PAIR_2=$SEQDATA_DIR/Sample_3-PxPP7/3-PxPP7_TCCGGAGA-TATAGCCT_L001_R2_001.fastq.gz
SAM_OUT=$OUTPUT_DIR/$LIBRARY.pxPP7.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &


# pxGP9 sample
PAIR_1=$SEQDATA_DIR/Sample_5-PxGP9/5-PxGP9_CTTGTAAT-TCTTTCCC_L001_R1_001.fastq.gz
PAIR_2=$SEQDATA_DIR/Sample_5-PxGP9/5-PxGP9_CTTGTAAT-TCTTTCCC_L001_R2_001.fastq.gz
SAM_OUT=$OUTPUT_DIR/$LIBRARY.pxGP9.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &


# pxGP1B sample
PAIR_1=$SEQDATA_DIR/Sample_4-PxGP1B/4-PxGP1B_GCCAATAT-TCTTTCCC_L001_R1_001.fastq.gz
PAIR_2=$SEQDATA_DIR/Sample_4-PxGP1B/4-PxGP1B_GCCAATAT-TCTTTCCC_L001_R2_001.fastq.gz
SAM_OUT=$OUTPUT_DIR/$LIBRARY.pxGP1B.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &


# pxPP6 sample
PAIR_1=$SEQDATA_DIR/Sample_2-PxPP6/2-PxPP6_ATTACTCG-ATAGAGGC_L001_R1_001.fastq.gz
PAIR_2=$SEQDATA_DIR/Sample_2-PxPP6/2-PxPP6_ATTACTCG-ATAGAGGC_L001_R2_001.fastq.gz
SAM_OUT=$OUTPUT_DIR/$LIBRARY.pxPP6.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &
