#!/bin/bash

SEQDATA_DIR=/pub20/arjen

echo " Processing $SEQDATA_DIR"

SAMPLE=1
MEDIAN_INSERT_SIZE=500
MIN_INSERT_SIZE=200
MAX_INSERT_SIZE=500
LIBRARY=PLUTHGAP

BOWTIE_INDEX=$HOME/Plutella/sequenceStorage/HGAP_NOV2014_polished
OUTPUT_DIR=$HOME/Plutella/BowtieMappings/HGAP_polished

PAIR_1=$SEQDATA_DIR/PxPP6_trimmed1.fastq
PAIR_2=$SEQDATA_DIR/PxPP6_trimmed2.fastq


RGINFO="--rg-id sample:$SAMPLE --rg SM:$SAMPLE --rg LB:$LIBRARY --rg PI:$MEDIAN_INSERT_SIZE --rg PL:ILLUMINA"
PAIR_MAP_ARGS="--fr -I $MIN_INSERT_SIZE -X $MAX_INSERT_SIZE"	

SAM_OUT=$OUTPUT_DIR/$LIBRARY.sam

bowtie2 -p 20 $PAIR_MAP_ARGS $RGINFO -x $BOWTIE_INDEX -1 $PAIR_1 -2 $PAIR_2 -S $SAM_OUT &

